### ISSUE TITLE
cli config

### ISSUE THREAD

**Issue by rudiars** [rppicomidi/midi2usbhub#1]
hi sir, I build this project but I use pico (without W). and I can't configure device connection via cli, please help. thanks

**Comment by rppicomidi** [comment]
Hello @rudiars. I am sorry you are having issues. I will try to help. please give me more information. Are you able to see output on your serial port terminal?

**Comment by rudiars** [comment]
yes I can see output on UART 0,  but command input won't work. 
I try type : help, just come help on output,

**Comment by rppicomidi** [comment]
When the code starts running, do you see "Pico MIDI Host to MIDI UART Adapter" on the console? Do you see the the LED on the pico board blinking? If not, when you build the code, does the build output say "board is pico" ?

Is your console program configured to echo whatever you type? If it is, please disable that. If you do not see characters echoed when you type, you may not have the UART 0 RX pin on your Pico board correctly wired to the UART RX of your UART to USB converter.

Please help me out by attaching your console output and build output.

**Comment by rudiars** [comment]
yes, led blinking 
when usb plugged serial print information about device, usb midi and flashdisk detected

**Comment by rudiars** [comment]
![image](https://user-images.githubusercontent.com/23315037/215970072-9fb88039-d83d-49ce-9c39-511d875f63a6.png)
[](url)

**Comment by rppicomidi** [comment]
Thank you. The output looks OK. It feels to me like a hardware problem. But I have no evidence. Have you tested your hardware to make sure the console can receive input?  For example, you could try [This program](https://github.com/ambotaku/pico-getLine) on your hardware; I have not tried it but it should work.  [This project](https://github.com/rppicomidi/pico-embedded-cli) uses the same CLI that midi2usbhub uses but you will have to edit the CMakeLists.txt per the instructions in README.md on that project if you try it.

**Comment by rppicomidi** [comment]
@rudiars I have just retested the code midi2usbhub code with a regular Pico board. The CLI is working for me. I see you have a USB flash drive plugged in. The only other thing I can think of if it is not a hardware issue is some bug in the USB side. If you unplug everything from the USB host, does the CLI keyboard input work? In case the instructions and the code is not clear, the console keyboard is your PC's keyboard, not a keyboard connected to the Pico USB.

**Comment by rppicomidi** [comment]
@rudiars Please accept my apology. I did not fully understand your issue. I think your problem was actually a code bug on my part. I recently pushed some code changes to midi2usbhub to fix an issue with the CLI that happens when you don't build with DEBUG on.

I did not understand at the time you filed this issue  that the default command line cmake build was to have DEBUG off. That may explain the issue you are seeing. The fix I used worked in another project.

If you have time, would you please try the code again? Thank you for your understanding.

**Comment by rppicomidi** [comment]
No response after some time. I am closing this.
